# Generated by Django 5.2.5 on 2025-08-08 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, help_text='Height in centimeters', null=True)),
                ('weight_kg', models.FloatField(blank=True, help_text='Weight in kilograms', null=True)),
                ('diseases', models.TextField(blank=True, help_text='Any medical conditions or allergies')),
                ('goal', models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('maintain', 'Maintain Weight'), ('endurance', 'Build Endurance'), ('strength', 'Build Strength')], max_length=20)),
                ('activity_level', models.CharField(blank=True, choices=[('sedentary', 'Sedentary (little to no exercise)'), ('lightly_active', 'Lightly Active (light exercise 1-3 days/week)'), ('moderately_active', 'Moderately Active (moderate exercise 3-5 days/week)'), ('very_active', 'Very Active (hard exercise 6-7 days/week)'), ('extremely_active', 'Extremely Active (very hard exercise, physical job)')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('breakfast', models.TextField(blank=True)),
                ('lunch', models.TextField(blank=True)),
                ('dinner', models.TextField(blank=True)),
                ('snacks', models.TextField(blank=True)),
                ('water_intake', models.CharField(blank=True, help_text='e.g., 3-4 liters', max_length=50)),
                ('supplements', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('calories_target', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_target', models.PositiveIntegerField(blank=True, help_text='in grams', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diet_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='progress_photos/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('monday', models.TextField(blank=True)),
                ('tuesday', models.TextField(blank=True)),
                ('wednesday', models.TextField(blank=True)),
                ('thursday', models.TextField(blank=True)),
                ('friday', models.TextField(blank=True)),
                ('saturday', models.TextField(blank=True)),
                ('sunday', models.TextField(blank=True)),
                ('duration_weeks', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
